package httpapi

import (
	"bytes"
	"errors"
	"io"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestClientFamilyClassification(t *testing.T) {
	cases := map[string]string{
		"Claude-Code/1.0":                      "claude-code",
		"claude-code/1.0 (cli)":                "claude-code",
		"ClaudeDesktop/1.0.4":                  "claude-desktop",
		"CherryStudio/1.0.3":                   "cherry-studio",
		"Cherry Studio/0.9.22":                 "cherry-studio",
		"LobeChat/1.0.0":                       "lobe",
		"Chatbox/1.0.0":                        "chatbox",
		"NextChat/2.14":                        "nextchat",
		"OpenCat/1.0":                          "opencat",
		"Copilot/1.0":                          "copilot",
		"Cursor/0.40":                          "cursor",
		"Windsurf/1.0":                         "windsurf",
		"pi/1.2.3 (win32; bun/1.1.0; x64)":     "pi",
		"pi-coding-agent":                      "pi",
		"api/v1/status":                        "browser",
		"Anthropic/2.0":                        "anthropic",
		"OpenAI/Python 1.30.0":                 "openai-python",
		"OpenAI-API/1.0 ChatGPT/1.0":           "openai",
		"curl/8.5.0":                           "cli",
		"python-requests/2.31":                 "python",
		"node-fetch/3.0":                       "node",
		"PostmanRuntime/7.36":                  "postman",
		"Insomnia/2023.5":                      "insomnia",
		"Mozilla/5.0 (Windows NT 10.0; Win64)": "browser",
		"":                                     "unknown",
	}
	for ua, want := range cases {
		if got := ClientFamily(ua); got != want {
			t.Fatalf("ClientFamily(%q) = %q, want %q", ua, got, want)
		}
	}
}

func TestClientFamilyOf(t *testing.T) {
	newReq := func(ua string) *http.Request {
		req := httptest.NewRequest(http.MethodPost, "/v1/chat/completions", nil)
		if ua != "" {
			req.Header.Set("User-Agent", ua)
		}
		return req
	}
	// UA classification unchanged.
	if got := ClientFamilyOf(newReq("Claude-Code/1.0")); got != "claude-code" {
		t.Fatalf("ua claude-code → %q", got)
	}
	if got := ClientFamilyOf(newReq("")); got != "unknown" {
		t.Fatalf("empty ua → %q", got)
	}
	// X-Meta-Client header overrides UA.
	req := newReq("curl/8.0")
	req.Header.Set("X-Meta-Client", "cursor")
	if got := ClientFamilyOf(req); got != "cursor" {
		t.Fatalf("declared cursor → %q", got)
	}
	// Unknown declared family is ignored, falls back to UA.
	req = newReq("curl/8.0")
	req.Header.Set("X-Meta-Client", "hacker-tool")
	if got := ClientFamilyOf(req); got != "cli" {
		t.Fatalf("invalid declared header must fall back: %q", got)
	}
	// Anthropic protocol signal: anthropic-version + /v1/messages.
	req = httptest.NewRequest(http.MethodPost, "/v1/messages", nil)
	req.Header.Set("anthropic-version", "2023-06-01")
	if got := ClientFamilyOf(req); got != "anthropic" {
		t.Fatalf("anthropic protocol → %q", got)
	}
	// anthropic-version on a chat path is not enough.
	req = httptest.NewRequest(http.MethodPost, "/v1/chat/completions", nil)
	req.Header.Set("anthropic-version", "2023-06-01")
	if got := ClientFamilyOf(req); got != "unknown" {
		t.Fatalf("anthropic-version alone → %q", got)
	}
}

func makeMultipartBody(t *testing.T, fields map[string]string, files map[string]string) ([]byte, string) {
	t.Helper()
	var body bytes.Buffer
	writer := multipart.NewWriter(&body)
	for name, value := range fields {
		if err := writer.WriteField(name, value); err != nil {
			t.Fatal(err)
		}
	}
	for name, value := range files {
		part, err := writer.CreateFormFile(name, name+".txt")
		if err != nil {
			t.Fatal(err)
		}
		if _, err := io.WriteString(part, value); err != nil {
			t.Fatal(err)
		}
	}
	if err := writer.Close(); err != nil {
		t.Fatal(err)
	}
	return body.Bytes(), writer.FormDataContentType()
}

func TestExtractMultipartModelParsesOnlyScalarModelField(t *testing.T) {
	var body bytes.Buffer
	writer := multipart.NewWriter(&body)
	file, err := writer.CreateFormFile("file", "image.png")
	if err != nil {
		t.Fatal(err)
	}
	// This byte sequence fooled the old raw-body scanner when the upload
	// preceded the real form field.
	if _, err := io.WriteString(file, "image-bytes\r\nname=\"model\"\r\n\r\nallowed-model"); err != nil {
		t.Fatal(err)
	}
	if err := writer.WriteField("model", "  blocked-model  "); err != nil {
		t.Fatal(err)
	}
	if err := writer.Close(); err != nil {
		t.Fatal(err)
	}

	model, err := extractMultipartModel(body.Bytes(), writer.FormDataContentType())
	if err != nil || model != "blocked-model" {
		t.Fatalf("model=%q err=%v", model, err)
	}
}

func TestExtractMultipartModelRejectsMissingDuplicateAndOversized(t *testing.T) {
	// Build the cases separately so each content type keeps the matching
	// boundary generated by its writer.
	body, ct := makeMultipartBody(t, map[string]string{"prompt": "x"}, nil)
	if _, err := extractMultipartModel(body, ct); !errors.Is(err, errMultipartModelMissing) {
		t.Fatalf("missing model err=%v", err)
	}

	var duplicate bytes.Buffer
	w := multipart.NewWriter(&duplicate)
	_ = w.WriteField("model", "one")
	_ = w.WriteField("model", "two")
	_ = w.Close()
	if _, err := extractMultipartModel(duplicate.Bytes(), w.FormDataContentType()); !errors.Is(err, errMultipartModelDuplicate) {
		t.Fatalf("duplicate model err=%v", err)
	}

	large := strings.Repeat("x", maxMultipartModelBytes+1)
	body, ct = makeMultipartBody(t, map[string]string{"model": large}, nil)
	if _, err := extractMultipartModel(body, ct); !errors.Is(err, errMultipartModelTooLarge) {
		t.Fatalf("oversized model err=%v", err)
	}
}

func TestExtractMultipartModelRejectsMalformedContentType(t *testing.T) {
	if _, err := extractMultipartModel([]byte("anything"), "multipart/form-data"); !errors.Is(err, errMultipartInvalid) {
		t.Fatalf("malformed content type err=%v", err)
	}
}

func TestExtractMultipartModelPreservesBodyBytes(t *testing.T) {
	body, contentType := makeMultipartBody(t, map[string]string{"model": "gpt-image-1"}, nil)
	want := append([]byte(nil), body...)
	if _, err := extractMultipartModel(body, contentType); err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(body, want) {
		t.Fatal("multipart parsing mutated forwarded body")
	}
}
