const zh = {
  teamDescription:
    "管理成员、授权与额度。个人／多用户模式在「概览」里切换；成员统一从 /console 登录。",
  personalSettings: "个人设置",
  personalSettingsHint: "只调整自己的调用偏好和界面，不改变站点或其他用户。",
  requestControls: "调用偏好",
  requestControlsHint: "已获站长授权。偏好只作用于自己的 Key，且不能突破站点与模型规则。",
  allowRequestControls: "允许用户调整故障转移与重试上限",
  managedByOwner: "调用策略由站长管理；当前只读。",
  failover: "跨渠道故障转移",
  inherit: "跟随站点",
  failoverOn: "允许在授权渠道内故障转移",
  failoverOff: "不进行跨渠道故障转移",
  retryLimit: "个人跨渠道重试上限（留空跟随站点）",
  siteDefault: "站点默认",
  effectiveDefault: "实际生效",
  retrySafetyHint:
    "个人上限只会收紧策略，模型级规则仍生效。关闭跨渠道转移不改变同渠道 Key 池策略；图像等非幂等请求仍不重试。",
  displayPreferences: "界面偏好",
  interfaceTheme: "界面主题",
  colorScheme: "配色模式",
  system: "跟随系统",
  light: "浅色",
  dark: "深色",
  density: "列表密度",
  comfortable: "舒适",
  compact: "紧凑",
  refresh: "刷新",
  all: "全部",
  moreActions: "更多操作",
  dangerZone: "危险操作",
  quotaUsedPercent: "已用 {percent}%",
  recordedTokens: "已记录 Tokens",
  currentKeysOnly: "当前密钥累计，不含已删除密钥",
  lastUsed: "最近调用",
  neverUsed: "尚未调用",
  searchKeys: "搜索名称、密钥提示或模型",
  searchModels: "搜索模型、供应商或能力",
  modelsWorkspaceHint: "浏览自己可用的模型、能力与授权候选；不暴露管理配置。",
  authorizedModels: "已授权模型",
  modelFamilies: "模型分组",
  authorizedCandidates: "已授权候选",
  capabilities: "能力",
  contextWindow: "上下文窗口",
  unspecified: "未提供",
  logs: "请求日志",
  export: "导出当前结果",
  loadedRequests: "当前结果请求数",
  successful: "成功",
  failedRequests: "失败",
  recordedCost: "已记录费用",
  searchRequests: "搜索请求 ID",
  allModelsShort: "全部模型",
  allStatuses: "全部状态",
  invalidTimeRange: "结束时间不能早于开始时间",
  requestDetails: "详情",
  attempts: "上游尝试",
  inputTokens: "输入 Tokens",
  outputTokens: "输出 Tokens",
  cacheRead: "缓存读取",
  cacheWrite: "缓存写入",
  team: "用户管理",
  mode: "运行模式",
  currentMode: "当前模式",
  personal: "个人模式",
  enabled: "团队模式",
  modeHint: "个人模式保持原控制台；团队模式启用成员账户，成员统一从 /console 登录。",
  disableHint:
    "切回个人模式会退出所有团队会话，阻止团队 Key 后续调用；用户、配置和历史保留。原个人 Key 不受影响。",
  members: "成员与邀请",
  navGroupMembers: "成员与权限",
  navGroupAccess: "接入与界面",
  policies: "权限与路由",
  branding: "成员界面",
  save: "保存",
  saving: "保存中…",
  cancel: "取消",
  close: "关闭",
  edit: "编辑",
  delete: "删除",
  copy: "复制",
  copied: "已复制",
  noKeysYet: "还没有启用中的令牌，先到「令牌」页创建一把。",
  copyDenied: "自动复制失败，请手动选中复制。",
  load: "加载中…",
  retry: "重试",
  failed: "操作失败",
  success: "已保存",
  name: "名称",
  username: "用户名",
  password: "密码",
  currentPassword: "当前密码",
  passwordHint: "长度不限",
  userHint: "3–64 位字母、数字、下划线、点或短横线",
  owner: "站长",
  admin: "管理员",
  member: "普通用户",
  role: "角色",
  status: "状态",
  active: "正常",
  paused: "已暂停",
  pause: "暂停",
  restore: "恢复",
  bootstrap: "创建站长账户",
  bootstrapAuto:
    "切换到团队模式时会自动用部署管理员创建站长（用户名与口令沿用当前管理员），无需另外填写。",
  bootstrapHint: "仅当部署没有可用的管理员口令时，才需要在这里手动创建站长。",
  totp: "原控制台两步验证码（如已开启）",
  ownerReady: "站长账户已创建",
  invite: "邀请用户",
  invites: "邀请记录",
  inviteHint: "单次邀请，7 天有效；不依赖邮件服务。",
  linkOnce: "此链接只显示一次，请复制后妥善保管。",
  label: "邀请备注",
  revoke: "撤销",
  pending: "待接受",
  consumed: "已接受",
  expired: "已过期",
  revoked: "已撤销",
  search: "搜索用户",
  keys: "令牌",
  keyCount: "Key 数",
  policy: "访问策略",
  details: "管理",
  userDetails: "用户详情",
  recovery: "生成账户恢复链接",
  revokeSessions: "退出该用户的所有会话",
  protectedOwner: "站长账户不可停用或降级",
  userChangeHint: "变更会撤销该用户的现有登录会话。暂停与恢复不会覆盖 Key 自身的启停状态。",
  policiesHint:
    "这里决定成员能用什么：模型名，以及这些模型能由哪些渠道承接。额度与限速不在这一页，在「额度」板块。默认策略不授予任何渠道，请先配置。",
  newPolicy: "新增策略",
  allModels: "允许调用所有模型",
  modelList: "按模型名授权（每行一个；空列表且未勾选上一项时，这个策略下没有任何模型可调）",
  maxKeys: "每人最多 Key 数",
  rpm: "每人每分钟请求数",
  routing: "允许个人路由",
  candidates: "按渠道授权（公共候选）",
  candidatesHint:
    "决定上面授权到的模型能由哪些渠道承接，也决定故障转移范围。勾选一个候选会同时把它的模型名加进上面的列表（取消勾选不会移除已加的模型名）。",
  none: "暂无数据",
  noCandidates: "还没有公共路由成员。请先在模型页配置路由。",
  publicName: "站点名称",
  logo: "Logo 地址（HTTP/HTTPS，可留空）",
  accent: "主色",
  notice: "公告",
  loginDescription: "登录页说明",
  apiURL: "公开 API Base URL（包含 /v1，可留空）",
  showUsage: "开放用量记录",
  showRouting: "开放个人路由页面",
  console: "管理控制台",
  logout: "退出登录",
  account: "账户",
  models: "模型与接入",
  usage: "用量记录",
  plans: "个人路由",
  login: "登录",
  loginHint: "使用账户登录，再创建属于自己的 API Key。",
  accept: "接受邀请",
  recover: "恢复账户",
  backLogin: "返回登录",
  invalidInvite: "链接缺少一次性凭证，请重新打开完整链接。",
  createKey: "创建 API Key",
  keyHint: "为不同应用创建独立密钥，权限继承你的账户策略。",
  advanced: "高级设置",
  expires: "过期时间（可留空）",
  ips: "允许的 IP/CIDR（每行一个，可留空）",
  keyModels: "进一步限制模型（逗号分隔，留空继承账户）",
  selectPlan: "路由方案",
  defaultRoute: "使用授权范围内的默认路由",
  connect: "接入",
  newKey: "密钥已创建",
  plaintextHint: "请勿把真实密钥放入公开仓库、截图或分享链接。",
  rotate: "轮换",
  rotationWarning: "轮换后旧密钥立即失效，确定继续？",
  deletionWarning: "确认删除？调用凭据将撤销，历史记录仍保留。",
  enable: "启用",
  disable: "停用",
  copyConfig: "复制配置",
  reveal: "查看密钥",
  model: "模型",
  importClient: "在 CC Switch 中导入",
  importWarning: "将把这把密钥交给本机 CC Switch。请勿转发包含密钥的链接。是否继续？",
  importStarted: "已发起打开应用；请在客户端确认，尚未验证导入结果。",
  noModels: "暂无获授权的可用模型，请联系管理员。",
  getStarted: "选择一把 Key 后，在接入页生成配置。",
  noKeys: "创建你的第一把 API Key",
  usageHint: "最多显示所选时间范围内最近 200 次请求。未上报用量显示“—”，不估算 token。",
  from: "起始日期",
  until: "结束日期",
  allKeys: "全部 Key",
  requestID: "请求 ID",
  tokens: "Tokens",
  latency: "耗时",
  apply: "应用",
  sessions: "登录会话",
  currentSession: "当前会话",
  created: "创建时间",
  changePassword: "修改密码并退出所有会话",
  passwordChanged: "密码已修改，请重新登录。",
  newPlan: "新建方案",
  planHint: "只对绑定此方案的本人 Key 生效，不修改公共默认路由。",
  priority: "优先级",
  weight: "权重",
  bindPlan: "保存后，在 Key 编辑页选择此方案。",
  accessDenied: "没有权限访问此功能",
  teamOff: "团队服务未开启",
  on: "启用",
  off: "停用",
  noData: "没有符合条件的记录",
  error: "错误",
  confirm: "确认",
  policyInUse: "策略仍被用户或邀请引用，不能删除",
  policyChanged: "策略立即影响关联用户及其 Key，是否保存？",
  arrange: "编排",
  modelsArrangeHint: "编排每个模型的上游顺序，只影响你自己的请求。",
  arrangeHint: "拖动调整上游顺序：顺序就是故障转移时尝试的先后；关掉的上游不参与你的请求。",
  arrangeSaved: "已保存",
  arrangedBadge: "已自定义",
  arrangeEmpty: "该模型暂无可编排的上游",
  restoreSiteOrder: "恢复站点默认顺序",
  restored: "已恢复站点顺序",
  upstreamWeight: "权重",
  participate: "参与",
  moveUp: "上移",
  moveDown: "下移",
  dragHandle: "拖动排序",
  planScope: "编辑方案",
  myDefaultOrder: "我的默认顺序",
  newPlanOption: "新建方案…",
  planName: "方案名称",
  siteDefaults: "站点默认",
  originUpstream: "上游模型",
  sameAsRouteName: "同名转发",
  // —— team codes ——
  codes: "注册码与兑换码",
  codesHint:
    "批量生成邀请码（注册用）和额度码（给已有成员充值）。明文码只在生成时显示一次，请当场复制。",
  codeKind: "码类型",
  codeKindInvite: "注册码",
  codeKindCredit: "额度码",
  codeKindInviteHint: "凭码在 /console 注册新账户",
  codeKindCreditHint: "登录后在个人设置里充入 Token 额度",
  codeMint: "生成码",
  codeCount: "数量",
  codeMaxUses: "每个码可用次数",
  codeExpiry: "有效期",
  codeExpiryHours: "{n} 小时",
  codeQuota: "附带额度（token）",
  codeQuotaCost: "附带额度（金额）",
  codeLabelHint: "例如 10 月新学员",
  codeFormHint:
    "注册码可用多次时，每个码可以被不同账户重复使用；额度码每个账户只能用同一个码一次。",
  codeMinted: "已生成 {n} 个码",
  codeMintedOnce: "这些码只显示这一次，关闭后无法再取回；请立即复制或发送给成员。",
  copyAll: "复制全部",
  codeEmpty: "还没有生成任何码。",
  codeRevokeWarning: "作废后该码立即失效，已注册的账户不受影响。确认作废？",
  uses: "已用 / 上限",
  // —— member administration ——
  newMember: "新建成员",
  create: "创建",
  memberCreatedHint: "账户已创建，下面是一次性显示的初始密码，请立即交给成员：",
  passwordOptional: "留空则自动生成随机密码",
  importMembers: "批量导入",
  import: "导入",
  importList: "成员列表",
  importHint: "每行一个成员：用户名, 名字, 密码（可省略）, 额度（可省略，支持 500k）",
  importSummary: "成功创建 {n} 个账户，密码仅显示这一次：",
  importFailures: "{n} 行未能导入：",
  copyCredentials: "复制账号与密码",
  quota: "Token 额度",
  quotaHint: "单位 token，0 表示不限。它与令牌、租户分组各自的限额同时生效，任一先耗尽即拒绝请求。",
  quotaUsed: "已用 {used}，总额 {total}",
  quotaEditSemantics:
    "留空或 0 表示不限额；Token 上限必须为整数，金额按 USD 账本单位填写。降低上限不会清零已用量，只有勾选重置才会清零。",
  quotaTotal: "Token 额度上限",
  quotaCostTotal: "金额额度",
  quotaCostHint: "按站点货币计价；与 Token 额度同时生效，先用尽者拒绝请求。",
  quotaReset: "重置用量",
  quotaResetHint: "清零已用计数，常用于充值续期",
  quotaResetLabel: "把这名成员已用额度清零",
  unlimited: "不限",
  editQuota: "调整额度",
  code: "注册码",
  codeHint: "站长发给你的邀请码 / 注册码",
  haveCode: "我有注册码",
  staleBundle: "页面已更新，当前标签页是旧版本；刷新一次即可继续。",
  oauth: "第三方登录",
  oauthHint: "允许成员用 GitHub / Linux.do 登录。回调地址必须原样填到对方的应用设置里。",
  oauthRegistration: "首次登录",
  oauthAutoRegister: "允许自助注册",
  oauthAutoRegisterHint:
    "开启后，任何人通过第三方登录都会自动建号（用下方策略）；关闭则只能登录已有账户。",
  oauthDefaultPolicy: "新账户策略",
  oauthFirstPolicy: "站点第一个策略",
  oauthEnable: "启用 {name} 登录",
  oauthCallbackHint: "把这个地址填到对方的「回调地址 / Redirect URI」里，否则无法登录。",
  oauthClientID: "Client ID",
  oauthClientSecret: "Client Secret",
  oauthSecretStored: "已保存",
  oauthSecretKeep: "留空则保留现有密钥",
  oauthScopes: "Scopes",
  oauthAdvanced: "高级：自定义端点",
  oauthAdvancedHint: "留空使用官方地址。指向其他地址可用于自建代理或测试环境。",
  oauthAuthorizeURL: "授权端点",
  oauthTokenURL: "Token 端点",
  oauthUserInfoURL: "用户信息端点",
  oauthReady: "已就绪：登录页会出现这个按钮。",
  oauthNotReady: "未就绪：填好 Client ID / Secret 并启用后才会出现在登录页。",
  oauthSignInWith: "使用 {name} 登录",
  oauthOr: "或",
  oauthBindings: "登录方式",
  oauthBindingsHint: "该成员已绑定的第三方账号；解绑只影响登录，不删除账户。",
  oauthNoBindings: "未绑定任何第三方账号。",
  oauthUnlink: "解绑",
  oauthUnlinkWarning: "解绑后该成员将无法再用这个账号登录。确认解绑？",
  credit: "Token 额度",
  creditHint: "额度由站长分配或兑换码充入；与每个 Key 自身的配额是两重限制，先到者生效。",
  creditRemaining: "剩余",
  creditUsed: "已用",
  creditTotal: "总额",
  redeemCode: "兑换码",
  redeemHint: "输入站长发的额度码，充入本账户",
  redeem: "兑换",
  redeemSuccess: "已充入 {n} token",
  creditCostRemaining: "金额剩余",
  creditCostUsed: "金额已用",
  redeemSuccessCost: "已充入 {amount}",
  bulkActions: "批量操作",
  bulkSelected: "已选 {n} 名成员",
  bulkPolicy: "批量改策略",
  applyPolicy: "改为策略：{name}",
  applyBulk: "应用",
  resume: "恢复",
  clearSelection: "取消选择",
  selectAll: "全选",
  selectMember: "选择 {name}",
  bulkDeleteWarning:
    "将永久删除选中的 {n} 名成员，并同时收回他们的 API Key 与登录会话。此操作不可恢复，确认继续？",
  "importReason.invalid_username": "用户名不合法（3–64 位字母数字，可含 . _ -）",
  "importReason.username_taken": "用户名已被占用",
  "importReason.invalid_quota": "额度格式不正确",
  "importReason.invalid_request": "该行内容不完整",
  "importReason.password_length": "密码不能为空",
  "importReason.invalid_policy": "策略不存在",
  "importReason.save_failed": "写入失败，请重试",

  // 多用户模块的板块与说明（每个板块在自己的路由页里）。
  overview: "概览",
  quotas: "额度",
  pricing: "计价",
  overviewHint:
    "这里是多用户能力的开关。开启后，控制台会多出成员、权限、额度与计价板块，成员统一从 /console 登录。",
  moduleMap:
    "成员决定谁能用；权限决定能调什么模型；额度决定能用多少；兑换码用于开户与充值；登录方式与成员界面决定成员怎么进来、看到什么。",
  quotasIntro:
    "一次中继请求要同时通过三层额度：令牌、它绑定的租户分组、以及令牌所属账户。每层都有 token 与金额两个独立预算，任一耗尽即拒绝该请求。",
  groupQuotas: "租户分组额度",
  groupQuotasHint:
    "分组的额度与限速。把令牌绑到某个分组（在令牌编辑里）后生效；未绑定的令牌走默认分组。注意它与「访问策略」是两件事：策略决定成员能用什么模型，分组决定能用多少、多快。",
  newGroup: "新建分组",
  quotaGroupTitle: "分组 · {name}",
  groupDeleteWarning: "删除分组「{name}」？已绑定该分组的令牌会退回默认分组。",
  quotaTokensShort: "Token 额度",
  quotaCostShort: "金额额度",
  memberQuotas: "成员额度",
  memberQuotasHint: "每个账户的两个预算；在成员详情里修改，与令牌、分组额度同时生效。",
  rateBurst: "突发额度",
  pricingIntro:
    "计价顺序：路由成员单价 → 模型单价（取最具体且有价的一层，整层替换），再乘以模型倍率。缓存读取未设单价时按输入价计费。",
  billingRatios: "计费倍率",
  billingRatiosHint: "倍率乘在该模型的最终单价上，影响全站账单；1 表示不加价，留空即不设置。",
  newRatio: "新增倍率",
  ratioLabel: "倍率",
  ratioHint: "0–1000，1 为原价。",
  ratioTitle: "倍率 · {model}",
  ratioDeleteWarning: "移除「{model}」的倍率？该模型回到 1 倍计价。",
  noRatios: "还没有模型倍率，所有模型都按 1 倍计价。",
  unitPrices: "单价在哪里改",
  unitPricesHint:
    "模型单价在模型页的「能力与元数据」里；渠道专属单价（含按次计费）在模型页的路由成员对话框里。两者优先级：成员单价优先于模型单价。",

  // 工作台（成员用自己的令牌试调；走真实转发，正常计费）。
  workbench: "工作台",
  wbIntro:
    "用自己的令牌试调模型。请求走网关的真实转发路径，因此会计入你自己的用量与费用，也会出现在请求日志里。",
  wbToken: "用哪个令牌",
  wbNoToken: "还没有启用中的令牌，先到「令牌」页创建一把再来试调。",
  wbModel: "模型",
  wbPrompt: "提示词",
  wbSend: "发送",
  wbSending: "等待上游响应…",
  wbResult: "响应",
  wbEmpty: "还没有发送过请求。",
  wbUsage: "本次用量",
  wbUsageNote: "费用按网关的计价规则记账，可在「总览」里看累计。",
  wbText: "文字",
  wbImage: "图像",
  imgTitle: "图像请求",
  imgGenerate: "生成",
  imgEdit: "编辑",
  imgSize: "尺寸",
  imgReference: "参考图",
  imgReferenceHint: "编辑要上传一张参考图（PNG / JPEG / WebP）。",
  imgNoReference: "请先选择参考图。",
  imgNoModels: "目录里没有声明输出图像能力的模型。",
  imgResult: "结果",
  imgEmpty: "还没有生成过图片。",
};
const en: Record<keyof typeof zh, string> = {
  teamDescription:
    "Manage members, access and credit. The personal / multi-user mode switches on the Overview board; members sign in at /console like everyone else.",
  personalSettings: "Personal settings",
  personalSettingsHint:
    "Change only your own request preferences and interface, never the site or other users.",
  requestControls: "Request preferences",
  requestControlsHint:
    "Enabled by your owner. These preferences only affect your keys and cannot override site or model rules.",
  allowRequestControls: "Allow user failover and retry preferences",
  managedByOwner: "Request policy is managed by the owner. These controls are read-only.",
  failover: "Cross-channel failover",
  inherit: "Inherit site policy",
  failoverOn: "Allow failover within authorized channels",
  failoverOff: "Do not fail over across channels",
  retryLimit: "Personal cross-channel retry cap (empty inherits)",
  siteDefault: "Site default",
  effectiveDefault: "Effective for you",
  retrySafetyHint:
    "Your cap can only narrow policy; model rules still apply. Disabling cross-channel failover does not change same-channel key-pool policy. Non-idempotent image requests are never retried.",
  displayPreferences: "Interface preferences",
  interfaceTheme: "Interface theme",
  colorScheme: "Color scheme",
  system: "System",
  light: "Light",
  dark: "Dark",
  density: "List density",
  comfortable: "Comfortable",
  compact: "Compact",
  refresh: "Refresh",
  all: "All",
  moreActions: "More actions",
  dangerZone: "Danger zone",
  quotaUsedPercent: "{percent}% used",
  recordedTokens: "Recorded tokens",
  currentKeysOnly: "Current keys only; deleted keys excluded",
  lastUsed: "Last request",
  neverUsed: "Not used yet",
  searchKeys: "Search name, key hint or model",
  searchModels: "Search models, providers or capabilities",
  modelsWorkspaceHint:
    "Browse your models, capabilities and authorized candidates without exposing administration data.",
  authorizedModels: "Authorized models",
  modelFamilies: "Model families",
  authorizedCandidates: "Authorized candidates",
  capabilities: "Capabilities",
  contextWindow: "Context window",
  unspecified: "Not specified",
  logs: "Request logs",
  export: "Export current results",
  loadedRequests: "Requests in results",
  successful: "Successful",
  failedRequests: "Failed",
  recordedCost: "Recorded cost",
  searchRequests: "Search request ID",
  allModelsShort: "All models",
  allStatuses: "All statuses",
  invalidTimeRange: "End must not precede start",
  requestDetails: "Details",
  attempts: "Upstream attempts",
  inputTokens: "Input tokens",
  outputTokens: "Output tokens",
  cacheRead: "Cache read",
  cacheWrite: "Cache creation",
  team: "User management",
  mode: "Operating mode",
  currentMode: "Current mode",
  personal: "Personal",
  enabled: "Team",
  modeHint: "Personal keeps the original console. Team enables a separate user application.",
  disableHint:
    "Switching to personal revokes team sessions and blocks team keys. Accounts, settings and history remain. Existing personal keys are unaffected.",
  members: "Members & invitations",
  navGroupMembers: "Members & access",
  navGroupAccess: "Onboarding & UI",
  policies: "Access & routing",
  branding: "Member interface",
  save: "Save",
  saving: "Saving…",
  cancel: "Cancel",
  close: "Close",
  edit: "Edit",
  delete: "Delete",
  copy: "Copy",
  copied: "Copied",
  noKeysYet: "No enabled token yet — create one on the Tokens page first.",
  copyDenied: "Clipboard unavailable. Select and copy manually.",
  load: "Loading…",
  retry: "Retry",
  failed: "Operation failed",
  success: "Saved",
  name: "Name",
  username: "Username",
  password: "Password",
  currentPassword: "Current password",
  passwordHint: "No length limit",
  userHint: "3–64 letters, digits, underscores, dots or hyphens",
  owner: "Owner",
  admin: "Administrator",
  member: "Member",
  role: "Role",
  status: "Status",
  active: "Active",
  paused: "Paused",
  pause: "Pause",
  restore: "Restore",
  bootstrap: "Create owner account",
  bootstrapAuto:
    "Switching to team mode creates the owner from the deployment administrator automatically, reusing the admin username and secret — nothing to fill in.",
  bootstrapHint: "Only needed when the deployment has no admin secret to derive a password from.",
  totp: "Console two-factor code (if enabled)",
  ownerReady: "Owner account created",
  invite: "Invite member",
  invites: "Invitations",
  inviteHint: "Single use, valid for 7 days. No mail service required.",
  linkOnce: "Shown only once. Copy this link and keep it safe.",
  label: "Invitation note",
  revoke: "Revoke",
  pending: "Pending",
  consumed: "Accepted",
  expired: "Expired",
  revoked: "Revoked",
  search: "Search members",
  keys: "API Keys",
  keyCount: "Keys",
  policy: "Access policy",
  details: "Manage",
  userDetails: "Member details",
  recovery: "Create account recovery link",
  revokeSessions: "Revoke all user sessions",
  protectedOwner: "The owner cannot be paused or demoted",
  userChangeHint:
    "Changes revoke existing login sessions. Pausing or restoring does not override individual key states.",
  policiesHint:
    "This page decides what a member may use: model names, and which channels may serve them. Quotas and rate limits live on the Quotas board, not here. The default policy grants no channel until configured.",
  newPolicy: "New policy",
  allModels: "Allow every model",
  modelList:
    "Authorize by model name (one per line; an empty list with the box above unchecked denies every model)",
  maxKeys: "Maximum keys per user",
  rpm: "Requests per minute per user",
  routing: "Allow personal routing",
  candidates: "Authorize by channel (public candidates)",
  candidatesHint:
    "Decides which channels may serve the models authorized above, and therefore how far failover can go. Selecting a candidate also adds its model name to the list above (clearing the box does not remove a name already added).",
  none: "No data yet",
  noCandidates: "No public route members. Configure routes on the Models page first.",
  publicName: "Site name",
  logo: "Logo URL (HTTP/HTTPS, optional)",
  accent: "Accent",
  notice: "Announcement",
  loginDescription: "Login description",
  apiURL: "Public API base URL (including /v1, optional)",
  showUsage: "Enable usage records",
  showRouting: "Enable personal routing page",
  console: "Management console",
  logout: "Sign out",
  account: "Account",
  models: "Models & setup",
  usage: "Usage records",
  plans: "Personal routing",
  login: "Sign in",
  loginHint: "Sign in with your account, then create your own API keys.",
  accept: "Accept invitation",
  recover: "Recover account",
  backLogin: "Back to sign in",
  invalidInvite: "One-time token missing. Reopen the complete link.",
  createKey: "Create API Key",
  keyHint: "Separate keys for each application, inheriting your account policy.",
  advanced: "Advanced options",
  expires: "Expiry (optional)",
  ips: "Allowed IPs/CIDRs (one per line, optional)",
  keyModels: "Restrict models (comma-separated; empty inherits account)",
  selectPlan: "Route plan",
  defaultRoute: "Authorized default routing",
  connect: "Connect",
  newKey: "Key created",
  plaintextHint: "Never publish real keys in repositories, screenshots or shared links.",
  rotate: "Rotate",
  rotationWarning: "Rotation invalidates the old key immediately. Continue?",
  deletionWarning: "Delete this credential? Access will be revoked; historical records remain.",
  enable: "Enable",
  disable: "Disable",
  copyConfig: "Copy configuration",
  reveal: "Reveal key",
  model: "Model",
  importClient: "Import into CC Switch",
  importWarning:
    "This passes the key to your local CC Switch application. Do not share the generated link. Continue?",
  importStarted: "Opening the application. Confirm there; import success has not been verified.",
  noModels: "No authorized models are available. Contact your administrator.",
  getStarted: "Choose a key to generate application configuration.",
  noKeys: "Create your first API Key",
  usageHint:
    "Shows up to 200 recent requests in the selected range. Missing usage is shown as “—”, never estimated.",
  from: "From",
  until: "Until",
  allKeys: "All keys",
  requestID: "Request ID",
  tokens: "Tokens",
  latency: "Latency",
  apply: "Apply",
  sessions: "Login sessions",
  currentSession: "Current session",
  created: "Created",
  changePassword: "Change password and revoke all sessions",
  passwordChanged: "Password changed. Sign in again.",
  newPlan: "New plan",
  planHint: "Only affects your keys bound to this plan, never public defaults.",
  priority: "Priority",
  weight: "Weight",
  bindPlan: "After saving, select this plan when editing a key.",
  accessDenied: "You do not have permission",
  teamOff: "Team service is not enabled",
  on: "Enabled",
  off: "Disabled",
  noData: "No matching records",
  error: "Error",
  confirm: "Confirm",
  policyInUse: "This policy is referenced by users or invitations",
  policyChanged: "This immediately affects associated users and keys. Save?",
  arrange: "Arrange",
  modelsArrangeHint: "Arrange each model's upstreams — it changes your own requests only.",
  arrangeHint:
    "Drag to set the order: it is the sequence failover walks. Upstreams you switch off never serve your requests.",
  arrangeSaved: "Saved",
  arrangedBadge: "Arranged",
  arrangeEmpty: "No upstream to arrange for this model yet",
  restoreSiteOrder: "Restore site order",
  restored: "Site order restored",
  upstreamWeight: "Weight",
  participate: "Serves",
  moveUp: "Move up",
  moveDown: "Move down",
  dragHandle: "Drag to reorder",
  planScope: "Editing plan",
  myDefaultOrder: "My default order",
  newPlanOption: "New plan…",
  planName: "Plan name",
  siteDefaults: "Site default",
  originUpstream: "Upstream model",
  sameAsRouteName: "Forwarded as-is",
  // —— team codes ——
  codes: "Codes",
  codesHint:
    "Mint signup codes and credit vouchers in batches. A code is shown once, at mint time — copy it then.",
  codeKind: "Kind",
  codeKindInvite: "Signup code",
  codeKindCredit: "Credit code",
  codeKindInviteHint: "Registers a new account at /console",
  codeKindCreditHint: "Redeemed in Personal settings to top up the account",
  codeMint: "Generate codes",
  codeCount: "Count",
  codeMaxUses: "Uses per code",
  codeExpiry: "Valid for",
  codeExpiryHours: "{n} hours",
  codeQuota: "Credit (tokens)",
  codeQuotaCost: "Credit (money)",
  codeLabelHint: "e.g. October cohort",
  codeFormHint:
    "With more than one use, different people can register with the same signup code; a credit code can be redeemed once per account.",
  codeMinted: "{n} codes generated",
  codeMintedOnce: "These are shown once and cannot be recovered after closing. Copy them now.",
  copyAll: "Copy all",
  codeEmpty: "No codes yet.",
  codeRevokeWarning:
    "Revoking kills the code immediately; accounts already registered stay. Continue?",
  uses: "Used / limit",
  // —— member administration ——
  newMember: "New member",
  create: "Create",
  memberCreatedHint: "Account created. This initial password is shown once — hand it over now:",
  passwordOptional: "Leave empty to generate a random password",
  importMembers: "Bulk import",
  import: "Import",
  importList: "Member list",
  importHint:
    "One member per line: username, name, password (optional), quota (optional, 500k accepted)",
  importSummary: "{n} accounts created. Passwords are shown once:",
  importFailures: "{n} lines could not be imported:",
  copyCredentials: "Copy credentials",
  quota: "Token credit",
  quotaHint:
    "In tokens; 0 means unlimited. It applies together with the token's own quota and its tenant group's — whichever runs out first refuses the request.",
  quotaUsed: "Used {used} of {total}",
  quotaEditSemantics:
    "Blank or 0 means unlimited. Token limits must be integers; money limits use ledger USD. Lowering a limit does not clear usage; only Reset clears counters.",
  quotaTotal: "Token credit limit",
  quotaCostTotal: "Spend allowance",
  quotaCostHint:
    "Priced in the site's currency and enforced beside the token allowance — whichever runs out first refuses the request.",
  quotaReset: "Reset usage",
  quotaResetHint: "Zeroes the used counter, which is what a top-up usually means",
  quotaResetLabel: "Reset this member's used credit to zero",
  unlimited: "Unlimited",
  editQuota: "Adjust credit",
  code: "Registration code",
  codeHint: "The signup code your operator gave you",
  haveCode: "I have a code",
  staleBundle: "The app was updated — this tab is running the old version. Refresh to continue.",
  oauth: "Third-party sign-in",
  oauthHint:
    "Let members sign in with GitHub or Linux.do. Register the callback URL at the provider exactly as shown.",
  oauthRegistration: "First sign-in",
  oauthAutoRegister: "Allow self-registration",
  oauthAutoRegisterHint:
    "On: anyone the provider vouches for gets an account on the policy below. Off: providers can only sign in to accounts that already exist.",
  oauthDefaultPolicy: "Policy for new accounts",
  oauthFirstPolicy: "The site's first policy",
  oauthEnable: "Enable {name} sign-in",
  oauthCallbackHint:
    "Paste this into the provider's redirect/callback setting, or sign-in cannot complete.",
  oauthClientID: "Client ID",
  oauthClientSecret: "Client secret",
  oauthSecretStored: "stored",
  oauthSecretKeep: "Leave blank to keep the stored secret",
  oauthScopes: "Scopes",
  oauthAdvanced: "Advanced: custom endpoints",
  oauthAdvancedHint:
    "Blank means the official endpoints. Pointing them elsewhere supports a self-hosted proxy or a test setup.",
  oauthAuthorizeURL: "Authorize endpoint",
  oauthTokenURL: "Token endpoint",
  oauthUserInfoURL: "Userinfo endpoint",
  oauthReady: "Ready: the button appears on the sign-in page.",
  oauthNotReady: "Not ready: it appears only with a client id, a secret and the switch on.",
  oauthSignInWith: "Sign in with {name}",
  oauthOr: "or",
  oauthBindings: "Sign-in methods",
  oauthBindingsHint:
    "Third-party accounts linked to this member. Unlinking removes a way in, not the account.",
  oauthNoBindings: "No third-party account linked.",
  oauthUnlink: "Unlink",
  oauthUnlinkWarning:
    "After unlinking this member can no longer sign in with that account. Continue?",
  credit: "Token credit",
  creditHint:
    "Granted by the operator or topped up with a code. It sits on top of each key's own quota — whichever runs out first applies.",
  creditRemaining: "Remaining",
  creditUsed: "Used",
  creditTotal: "Total",
  redeemCode: "Redemption code",
  redeemHint: "Paste a credit code from your operator to top up this account",
  redeem: "Redeem",
  redeemSuccess: "{n} tokens added",
  creditCostRemaining: "Spend left",
  creditCostUsed: "Spend used",
  redeemSuccessCost: "{amount} added",
  bulkActions: "Bulk actions",
  bulkSelected: "{n} members selected",
  bulkPolicy: "Change policy",
  applyPolicy: "Set policy: {name}",
  applyBulk: "Apply",
  resume: "Resume",
  clearSelection: "Clear selection",
  selectAll: "Select all",
  selectMember: "Select {name}",
  bulkDeleteWarning:
    "This permanently deletes {n} selected members and revokes their API keys and sessions. It cannot be undone. Continue?",
  "importReason.invalid_username": "Invalid username (3-64 alphanumerics, . _ - allowed)",
  "importReason.username_taken": "Username already taken",
  "importReason.invalid_quota": "Unreadable quota",
  "importReason.invalid_request": "Incomplete line",
  "importReason.password_length": "Password must not be empty",
  "importReason.invalid_policy": "Policy does not exist",
  "importReason.save_failed": "Write failed, retry",

  // Boards of the multi-user module (each is its own route).
  overview: "Overview",
  quotas: "Credit & quotas",
  pricing: "Pricing",
  overviewHint:
    "The switch for multi-user mode. Once it is on, the console gains boards for members, access, credit and pricing, and members sign in through the same /console page.",
  moduleMap:
    "Members decide who may call; access policies decide which models they may call; credit decides how much; codes open accounts and top them up; sign-in decides how they get in and what they see.",
  quotasIntro:
    "Every relay request must clear three budgets: the client token, the tenant group that token is bound to, and the account behind it. Each of the three holds two independent budgets — tokens and money — and whichever runs out first refuses the request.",
  groupQuotas: "Tenant group quotas",
  groupQuotasHint:
    "Quotas and rate limits per group. They apply once a client token is bound to the group (in the token editor); unbound tokens use the default group. This is a different axis from an access policy: the policy decides which models a member may use, a group decides how much and how fast.",
  newGroup: "New group",
  quotaGroupTitle: "Group · {name}",
  groupDeleteWarning: 'Delete group "{name}"? Tokens bound to it fall back to the default group.',
  quotaTokensShort: "Tokens",
  quotaCostShort: "Spend",
  memberQuotas: "Member credit",
  memberQuotasHint:
    "Each account's two budgets. Edited on the member's own page, and enforced together with the token's and the group's.",
  rateBurst: "Burst",
  pricingIntro:
    "Pricing order: the route member's unit price, then the model's (the most specific layer that is priced wins outright), multiplied by the model's billing multiplier. Cache reads fall back to the input price when no cache price is set.",
  billingRatios: "Billing multiplier",
  billingRatiosHint:
    "The multiplier applies on top of that model's final unit price and changes every account's bill; 1 means no markup. A model with no multiplier is billed at 1.",
  newRatio: "Add multiplier",
  ratioLabel: "Multiplier",
  ratioHint: "0–1000; 1 is list price.",
  ratioTitle: "Multiplier · {model}",
  ratioDeleteWarning: "Remove the multiplier for {model}? It returns to 1× pricing.",
  noRatios: "No multipliers yet — every model is billed at 1×.",
  unitPrices: "Where unit prices live",
  unitPricesHint:
    "A model's unit price is on the Models page under capability & metadata; a channel-specific price (including per-request billing) is in that model's route member dialog. A member price wins over a model price.",

  // Workbench: a member probing with their own token (real relay, real billing).
  workbench: "Workbench",
  wbIntro:
    "Probe a model with your own token. The request takes the gateway's real relay path, so it counts toward your usage and spend and appears in the request log.",
  wbToken: "Which token",
  wbNoToken: "No enabled token yet — create one on the Tokens page first.",
  wbModel: "Model",
  wbPrompt: "Prompt",
  wbSend: "Send",
  wbSending: "Waiting for the upstream…",
  wbResult: "Response",
  wbEmpty: "Nothing sent yet.",
  wbUsage: "This request",
  wbUsageNote: "Cost follows the gateway's own pricing rules and accumulates on the Overview page.",
  wbText: "Text",
  wbImage: "Image",
  imgTitle: "Image request",
  imgGenerate: "Generate",
  imgEdit: "Edit",
  imgSize: "Size",
  imgReference: "Reference image",
  imgReferenceHint: "Editing needs one reference image (PNG / JPEG / WebP).",
  imgNoReference: "Choose a reference image first.",
  imgNoModels: "No model in the catalogue declares image output.",
  imgResult: "Result",
  imgEmpty: "Nothing generated yet.",
};
export type TeamText = (key: keyof typeof zh, vars?: Record<string, string | number>) => string;
export type TeamKey = keyof typeof zh;
/**
 * Team copy, with optional `{name}` interpolation — a code board has to say
 * "3 codes minted" and an import has to name the account it created.
 */
export const teamText =
  (locale: string): TeamText =>
  (key, vars) => {
    const raw = (locale.startsWith("zh") ? zh : en)[key];
    if (!vars || !raw) return raw;
    return raw.replace(/\{(\w+)\}/g, (match, name) =>
      name in vars ? String(vars[name as keyof typeof vars]) : match,
    );
  };
export const teamError = (error: unknown, locale: string) => {
  const raw = error instanceof Error ? error.message : "";
  // A refused third-party sign-in arrives as a redirect parameter; the caller
  // wraps it as `oauth_error.<code>` so it is obvious where it came from. The
  // message table keys on the bare code.
  const code = raw.startsWith("oauth_error.") ? raw.slice("oauth_error.".length) : raw;
  const messages: Record<string, [string, string]> = {
    preferences_not_allowed: [
      "站长未开放调用偏好设置",
      "The owner has not enabled request preferences",
    ],
    invalid_preferences: [
      "请检查故障转移选项和重试上限（0–100）",
      "Check the failover option and retry cap (0–100)",
    ],
    mode_changed: ["运行模式已改变，请返回设置页确认", "Operating mode changed. Check Settings."],
    team_disabled: ["团队服务未开启", "Team service is not enabled"],
    invalid_credentials: ["用户名或密码不正确", "Invalid credentials"],
    password_length: [
      "密码不能为空，最多 1024 字节",
      "Password must not be empty, and at most 1024 bytes",
    ],
    invalid_username: ["用户名格式或显示名称不正确", "Invalid username or display name"],
    username_taken: ["用户名已被使用", "Username already exists"],
    invitation_invalid: [
      "邀请或恢复链接已失效、被撤销或已使用",
      "Invitation or recovery link is invalid or expired",
    ],
    csrf_failed: ["安全校验失败，请刷新页面后重试", "Security check failed. Reload and try again"],
    key_limit: ["已达到策略允许的 Key 数量上限", "Key limit reached"],
    invalid_members: ["存在未授权或无效的路由成员", "Unauthorized or invalid route members"],
    plan_in_use: [
      "方案正在使用或不存在，请先解除 Key 绑定",
      "Plan is in use or missing. Unbind keys first",
    ],
    policy_in_use: ["策略仍被引用，不能删除", "Policy is still referenced"],
    owner_protected: ["站长账户不可停用或降级", "Owner is protected"],
    owner_required: ["此操作仅限站长", "Owner permission required"],
    create_owner_first: ["请先创建站长账户", "Create the owner account first"],
    totp_required: ["请输入正确的原控制台两步验证码", "Console two-factor code is required"],
    invalid_policy: ["请检查策略名称、请求速率和 Key 数量", "Check policy name and limits"],
    invalid_key: ["请检查 Key 名称、过期时间和 IP 配置", "Check key name, expiry and IP rules"],
    account_login_required: ["登录已失效，请重新登录", "Please sign in again"],
    login_rate_limited: ["尝试过于频繁，请稍后重试", "Too many attempts. Try again later"],
    // A refused third-party sign-in: one message per code the callback can
    // redirect with, so the login page explains what actually went wrong.
    oauth_state_invalid: [
      "登录链接已过期或校验失败，请重新发起登录",
      "The sign-in link expired or failed verification. Start again.",
    ],
    oauth_state_missing: [
      "登录会话已丢失，请重新发起登录",
      "The sign-in session was lost. Start again.",
    ],
    oauth_cancelled: ["你取消了授权", "You cancelled the authorization"],
    oauth_provider_unavailable: [
      "该登录方式未启用或未配置",
      "That sign-in method is disabled or not configured",
    ],
    oauth_code_missing: [
      "第三方没有返回授权码，请重试",
      "The provider returned no code. Try again.",
    ],
    oauth_exchange_failed: [
      "换取令牌失败，请检查 Client Secret 与回调地址",
      "Token exchange failed — check the client secret and callback URL",
    ],
    oauth_account_paused: [
      "该账户已被暂停，请联系站长",
      "This account is paused. Contact the operator.",
    ],
    oauth_register_disabled: [
      "站长未开自助注册，请先获取邀请码或注册码",
      "Self-registration is off — ask for an invitation or signup code",
    ],
    oauth_no_policy: [
      "站点还没有可用的访问策略，请联系站长",
      "The site has no usable access policy yet. Contact the operator.",
    ],
    oauth_account_failed: [
      "建立账户失败，请联系站长",
      "Account creation failed. Contact the operator.",
    ],
    oauth_session_failed: ["登录会话创建失败，请重试", "Could not start a session. Try again."],
  };
  return (
    messages[code]?.[locale.startsWith("zh") ? 0 : 1] ??
    `${teamText(locale)("failed")}${code ? ` (${code})` : ""}`
  );
};
