// Command docsgen regenerates the machine-checkable half of the documentation
// site (docs/reference) from the code that owns each fact.
//
// It exists because "the docs drifted from the code" is the default outcome of
// hand-written reference tables. Every table it writes has one authoritative
// source in the repository, and CI re-runs this command and fails on any diff —
// so a new environment variable, endpoint, error category or migration cannot
// land without the documentation following it.
//
// Run from the repository root:
//
//	go run ./tools/docsgen
//
// Editing a generated file by hand is always wrong: the next run overwrites it.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

// generatedHeader marks a file as machine-owned. The HTML comment is invisible
// in the rendered site and obvious in the editor.
const generatedHeader = "<!-- GENERATED BY tools/docsgen — DO NOT EDIT BY HAND -->\n<!-- source: %s -->\n\n"

type generator struct {
	// file is the output basename under docs/reference.
	file string
	// source names the code the table is derived from, for the header.
	source string
	// run renders the markdown body (without the header).
	run func(root string) (string, error)
}

func generators() []generator {
	return []generator{
		{"env-vars.md", "internal/config/config.go", genEnvVars},
		{"runtime-settings.md", "internal/runtimeconfig/runtimeconfig.go", genRuntimeSettings},
		{"admin-api.md", "internal/httpapi（relay*.go 之外的 Register 方法）", genAdminAPI},
		{"public-api.md", "internal/httpapi/relay*.go", genPublicAPI},
		{"error-codes.md", "internal/proxy/proxy_classify.go + web/src/errorCatalog.ts", genErrorCodes},
		{"database-schema.md", "internal/store/*.sql", genDatabaseSchema},
		{"connection-types.md", "internal/adapters/adapters.go + web/src/connectionTypes.ts", genConnectionTypes},
		{"provider-profiles.md", "internal/proxy/provider_profile.go", genProviderProfiles},
	}
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "docsgen:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}
	outDir := filepath.Join(root, "docs", "reference")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	for _, g := range generators() {
		body, err := g.run(root)
		if err != nil {
			return fmt.Errorf("%s: %w", g.file, err)
		}
		content := fmt.Sprintf(generatedHeader, g.source) + body
		path := filepath.Join(outDir, g.file)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return err
		}
		fmt.Println("wrote", filepath.ToSlash(filepath.Join("docs", "reference", g.file)))
	}
	return nil
}

// repoRoot locates the repository root from this file's own path, so the
// command works regardless of the working directory it is invoked from.
func repoRoot() (string, error) {
	_, self, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("cannot resolve the generator's own path")
	}
	// <root>/tools/docsgen/main.go → <root>
	root := filepath.Dir(filepath.Dir(filepath.Dir(self)))
	if _, err := os.Stat(filepath.Join(root, "go.mod")); err != nil {
		return "", fmt.Errorf("no go.mod at %s: %w", root, err)
	}
	return root, nil
}
